# Громкость по умолчанию для персонального радио в уши (0 - 100)
default-volume: 20

# Максимально допустимая громкость для персонального радио
max-volume: 100

# Настройки 3D радио-кассет для проигрывателя
3d-radio:
  # Громкость вещания 3D-колонки в мире (0 - 100). 100 — максимальная громкость и мощный сочный звук!
  volume: 100
  default-distance: 15
  allowed-distances: [5, 10, 15, 20, 25, 30]

# Сохраненные пресеты радиостанций.
stations:
  maximum:
    name: "Maximum"
    genre: "Rock"
    url: "https://maximum.hostingradio.ru/maximum128.mp3"
  europa:
    name: "Europa Plus"
    genre: "Pop"
    url: "http://emgregion.hostingradio.ru:8064/moscow.europaplus.mp3"
  studio21:
    name: "Studio 21"
    genre: "Hip-Hop / Rap"
    url: "http://78.140.197.238:9877/msk_studio21"
  nashe:
    name: "Наше Радио"
    genre: "Rus Rock"
    url: "https://nashe1.hostingradio.ru/nashe-256"
  retro:
    name: "Ретро FM"
    genre: "Gold Retro"
    url: "http://emgregion.hostingradio.ru:8064/moscow.retrofm.mp3"
  Monte Carlo: "https://montecarlo.hostingradio.ru/montecarlo96.aacp"